# Generated by Django 5.0.3 on 2024-04-11 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periododecurso',
            options={'verbose_name_plural': 'periodos'},
        ),
        migrations.AlterModelOptions(
            name='turma',
            options={'verbose_name_plural': 'Turmas'},
        ),
        migrations.AlterField(
            model_name='turma',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.periododecurso'),
        ),
    ]
